language: ruby
rvm:
  - rbx-2
  - 1.9.3
  - 2.0.0
  - ruby-head
script: "bundle exec rake"
gemfile:
  - Gemfile
notifications:
  recipients:
    - lourens@methodmissing.com
    - matt.connolly@me.com
branches:
  only:
    - master
before_install:
  - ruby -v | grep rubinius > /dev/null && travis_retry gem install rubysl
matrix:
  allow_failures:
    - rvm: ruby-head