language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script: "bundle exec rake"
before_install: "sudo apt-get install uuid-dev"
gemfile:
  - Gemfile
notifications:
  recipients:
    - lourens@methodmissing.com
branches:
  only:
    - master